services:
  app:
    image: analytics-api:v1
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.app
    ports:
      - "8002:80"
    command: [".venv/bin/uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    volumes:
      - ./src:/code/src:rw
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: uv.lock
        - action: rebuild
          path: compose.yaml

  db_service:
    image: timescale/timescaledb:latest-pg17
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env.pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db_service

volumes:
  timescaledb_data: